sudo: false
language: node_js
node_js:
  - node
  - '6'
  - '4'
addons:
  code_climate:
    repo_token: e6b833ee868f17733abe9cc20c2e83a7bda1f4006d9fc4cb26a4ba1a0c05b088
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false
  slack:
    rooms:
      secure: nKis5Kh3/x2pRzpo+2E/XSzYI/rsCxYgOqktIHpdtpodC0cmhuHdnTPSlQ70+cuv/uovenQiiLtfN7vH2VOjJ62ZgD1OnglNjc3q6bGGYK75+fd2MdF5+n/zTGt0R0Mv14CIGNaJb3eXJZ9OQQkV3GUKFB31FDq56aNQIClWIfN8oys5CMGx3Nt1edw+yrvktIqk3O9A6HgJz6nX/w263ORbikvXVQmBomui8SO9VDs52evBlVqU6jpW8wwmnfaPBsV50wqmvXkgZjSkpYXB13EPVXn8gU9Vi3YI87Bicj3RaPPPb1LPRDT+5pEpSZbJVmhDIulotoiIDW4uqpo+Dxc5ejljIiM30Bu8UV31uyIHz61yYGquz5a50fdchtQSb7wqgjiLmLILWTvK/EPPUjv5sdkUfZ/Y2Cm6GNTzrFo98LlzDOW/W1p0nrbn3IbaChuZ92g9YuUWa9fS2zH2g3s9LBu4lrpWieBNlDA7iPo1e3L2Y9y5JYArYSr2VYJmgqH8PUzAmB0/760f8/mHpcnuRaWlP76bfA3ULs2IhOIteiQ7GB6O8PhIZ/1cN8ZHtybUVFrHDSF07cNHCLE0DNbeOXzY7SE+uwP8JMDt2hXxWvGmTZEonvFIkAirqlIUeVpG5ZrfJguJ4B/lSKrs2NvB9BOapQ3VSwt4+kp8jVk=
